langs = ["Hallo", "Përshëndetje", "ሰላም", "مرحبا",
         "Բարեւ Ձեզ", "Salam", "Kaixo", "добры дзень",
         "হ্যালো", "Zdravo", "Здравейте", "Hola",
         "Hello", "Moni", "你好", "Bonghjornu",
         "Zdravo", "Ahoj", "Hej", "Hallo",
         "Hello", "Saluton", "Tere", "Kamusta",
         "Hei", "Bonjour", "Hallo", "Ola",
         "გამარჯობა", "Hallo", "γεια σας", "નમસ્તે",
         "Bonjou", "Sannu", "Aloha", "שלום",
         "नमस्ते", "Nyob zoo", "Helló", "Halló",
         "Nnọọ", "Halo", "Dia dhuit", "Ciao",
         "こんにちは", "Halo", "ನಮಸ್ಕಾರ", "Сәлеметсіз бе",
         "ជំរាបសួរ", "Mwaramutse", "안녕하세요", "Slav",
         "салам", "ສະບາຍດີ", "Salve", "Sveiki",
         "Sveiki", "Hallo", "Здраво", "Salama",
         "Hello", "ഹലോ", "Bongu", "Kia ora",
         "नमस्कार", "Сайн уу", "ဟယ်လို", "नमस्त",
         "Hallo", "ନମସ୍କାର", "سلا" ,"سلام",
         "Witaj", "Olá", "ਸਤ ਸ੍ਰੀ ਅਕਾਲ", "Buna ziua",
         "Привет", "Talofa", "Halò", "Здрав",
         "Lumela", "Mhoro", "سلا", "ආයුබෝවන්",
         "Ahoj", "Zdravo", "Hello", "Hola",
         "Halo", "Habari", "Hej", "Салом",
         "வணக்கம்", "Сәлам", "హలో", "สวัสดี",
         "Merhaba", "Salam", "Здрастуйте", "ہیلو",
         "ياخشىمۇسىز", "Salom", "Xin chào", "Helo",
         "Mholweni", "העלא", "Pẹlẹ o", "Sawubona",]


list_of_language = ["afrikaans", "albanian", "amharic", "arabic",
                    "armenian", "azerbaijani", "basque", "belarusian",
                    "bengali", "bosnian", "bulgarian", "catalan",
                    "cebuano", "chichewa", "chinese (simplified)", "chinese (traditional)", "corsican",
                    "croatian", "czech", "danish", "dutch",
                    "english", "esperanto", "estonian", "filipino",
                    "finnish", "french", "frisian", "galician",
                    "georgian", "german", "greek", "gujarati"
                    "haitian creole", "hausa", "hawaiian", "hebrew",
                    "hebrew", "hindi", "hmong", "hungarian",
                    "icelandic", "igbo", "indonesian", "irish",
                    "italian", "japanese", "javanese", "kannada",
                    "kazakh", "khmer", "korean", "kurdish (kurmanji)",
                    "kyrgyz", "lao", "latin", "latvian",
                    "lithuanian", "luxembourgish", "macedonian", "malagasy",
                    "malay", "malayalam", "maltese", "maori",
                    "marathi", "mongolian", "myanmar (burmese)", "nepali",
                    "norwegian", "odia", "pashto", "persian",
                    "polish", "portuguese", "punjabi", "romanian",
                    "russian", "samoan", "scots gaelic", "serbian",
                    "sesotho", "shona", "sindhi", "sinhala",
                    "slovak", "slovenian", "somali", "spanish",
                    "sundanese", "swahili", "swedish", "tajik",
                    "tamil", "telugu", "thai", "turkish",
                    "ukrainian", "urdu", "uyghur", "uzbek",
                    "vietnamese", "welsh", "xhosa", "yiddish",
                    "yoruba", "zulu",]