langs = ["Hallo", "Përshëndetje", "ሰላም", "مرحبًا",
         "Բարեւ Ձեզ", "Salam", "Kaixo", "добры дзень",
         "হ্যালো", "zdravo", "Здравейте", "Hola",
         "Hello", "Moni", "你好", "你好",
         "Bonghjornu", "zdravo", "Ahoj", "Hej",
         "Hallo", "Hello", "Saluton", "Tere",
         "Kamusta", "Hei", "Bonjour", "Hallo",
         "Ola", "გამარჯობა", "Hallo", "γεια σας",
         "નમસ્તે", "Bonjou", "Sannu", "Aloha",
         "שלום", "नमस्ते", "Nyob zoo", "Helló",
         "Halló", "Nnọọ", "Halo", "Dia dhuit",
         "Ciao", "こんにちは", "Halo", "ನಮಸ್ಕಾರ",
         "Сәлеметсіз бе", "ជំរាបសួរ", "Mwaramutse", "여보세요",
         "Slav", "Салам", "ສະບາຍດີ", "Salve",
         "Sveiki", "Sveiki", "Hallo", "Здраво",
         "Salama", "Hello", "ഹലോ", "Bongu",
         "Kia ora", "नमस्कार", "Сайн уу", "မင်္ဂလာပါ",
         "नमस्ते", "Hallo", "ନମସ୍କାର" ,"سلام",
         "سلام", "Witam", "Olá", "ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
         "Buna ziua", "Привет", "talofa", "Halò",
         "Здраво", "Lumela", "Mhoro", "سلام",
         "ආයුබෝවන්", "Ahoj", "zdravo", "Hello",
         "Hola", "Halo", "Habari", "Hallå",
         "Салом", "வணக்கம்", "Сәлам", "హలో",
         "สวัสดี", "Merhaba", "", "",
         "", "", "", "",
         "", "", "", "",
         "", "", "", "",]


list_of_language = ["afrikaans", "albanian", "amharic", "arabic",
                    "armenian", "azerbaijani", "basque", "belarusian",
                    "bengali", "bosnian", "bulgarian", "catalan",
                    "cebuano", "chichewa", "chinese (simplified)", "chinese (traditional)",
                    "corsican", "croatian", "czech", "danish",
                    "dutch", "english", "esperanto", "estonian",
                    "filipino", "finnish", "french", "frisian", 
                    "galician", "georgian", "german", "greek",
                    "gujarati", "haitian creole", "hausa", "hawaiian",
                    "hebrew", "hebrew", "hindi", "hmong",
                    "hungarian", "icelandic", "igbo", "indonesian",
                    "irish", "italian", "japanese", "javanese",
                    "kannada", "kazakh", "khmer", "korean",
                    "kurdish (kurmanji)", "kyrgyz", "lao", "latin",
                    "latvian", "lithuanian", "luxembourgish", "macedonian",
                    "malagasy", "malay", "malayalam", "maltese",
                    "maori", "marathi", "mongolian", "myanmar (burmese)",
                    "nepali", "norwegian", "odia", "pashto",
                    "persian", "polish", "portuguese", "punjabi",
                    "romanian", "russian", "samoan", "scots gaelic",
                    "serbian", "sesotho", "shona", "sindhi",
                    "sinhala", "slovak", "slovenian", "somali",
                    "spanish", "sundanese", "swahili", "swedish",
                    "tajik", "tamil", "telugu", "thai",
                    "turkish", "ukrainian", "urdu", "uyghur",
                    "uzbek", "vietnamese", "welsh", "xhosa",
                    "yiddish", "yoruba", "zulu",]